### ISSUE TITLE
About some issues in util.py

### ISSUE THREAD

**Issue by LittleStarZz** [cnnlstm/FSLSD_HiRes#14]
from criteria.lpips.lpips import LPIPS
from criteria import w_norm
The error reported directly is, ModuleNotFoundError: No module named 'criteria',
Directly! pip install criteria, but found that the root quilt does not have this dependency, and the corresponding criteria.py file was not found in the source file. Where should I download and import this dependency?
Sorry to trouble you, if you see it, thank you for your reply!

**Comment by LittleStarZz** [comment]
Resolved, sorry to bother you

**Comment by philz1337x** [comment]
How did you solved the problem?

**Comment by AliceZhang2002** [comment]
How did you solve it？Can you share with me~
